version: '2'
services:
  app-lb:
    ports:
    - ${http_port}:${http_port}/tcp
    labels:
      io.rancher.loadbalancer.target.owncloud: ${onwcloud_hostname}:${http_port}=80
      io.rancher.scheduler.affinity:host_label: server=proxy
    tty: true
    image: rancher/load-balancer-service
    links:
    - owncloud:owncloud
    stdin_open: true
  owncloud:
    image: owncloud
    links:
      - db:mysql

  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${db_password}
