version: '2'
catalog:
  name: Dokuwiki
  version: v0.2-dokuwiki
  description: |
    Dokuwiki
  minimum_rancher_version: v0.56.0
  maintainer: "Dirceu Silva <contato@dirceusilva.com>"
  questions:
    - variable: "dokuwiki_hostname"
      description: "Hostname (domínio)"
      label: "Hostname:"
      required: true
      default: "dokuwiki"
      type: "string"
    - variable: "http_port"
      description: "Porta que será utilizada:"
      label: "Porta:"
      required: true
      default: 8080
      type: "int"
    - variable: volume_driver
      description: "Driver/Volume a ser utilizado para a persistência de dados"
      label: "Volume driver"
      required: true
      default: "rancher-nfs"
      type: enum
      options:
        - local
        - rancher-nfs

app-lb:
  scale: 1
  load_balancer_config:
    haproxy_config: {}
  health_check:
    port: 42
    interval: 2000
    unhealthy_threshold: 3
    strategy: recreate
    response_timeout: 2000
    healthy_threshold: 2

dokuwiki:
  scale: 1
