version: '2'
services:
  app-lb:
    ports:
    - ${http_port}:${http_port}/tcp
    labels:
      io.rancher.loadbalancer.target.owncloud: ${dokuwiki_hostname}:${http_port}=80
    tty: true
    image: rancher/load-balancer-service
    links:
    - dokuwiki:dokuwiki
    stdin_open: true
  dokuwiki:
    image: 'bitnami/dokuwiki:latest'
    ports:
      - '80:80'
      - '443:443'
    tty: true
    volumes:
      - 'dokuwiki_data:/bitnami'
volumes:
  dokuwiki_data:
    driver: local
        