---
name: Dokuwiki
description: >
  Dokuwiki
version: 0.0.1-rancher1-doku
category: Wiki
maintainer: Luiz Henrique <luiz@madeiracampos.com>
license: GNU GPL v3
projectURL: https://github.com/luiz-madeira/catalogs-rancher
