---
name: Dokuwiki
description: >
  Dokuwiki é um sistema de wiki leve, feito em php e não utiliza banco de dados.
version: 0.0.2-rancher1-doku
category: Wiki
maintainer: Luiz Henrique <luiz@madeiracampos.com>
license: GNU GPL v3
projectURL: https://github.com/luiz-madeira/catalogs-rancher
