version: '2'
volumes:
    gitlab-app-etc:
        driver: ${volume_driver}
        driver_opts:
            onRemove: retain
    git-lab-app-var-log:
        driver: ${volume_driver}
        driver_opts:
            onRemove: retain
    git-lab-app-var-opt:
        driver: ${volume_driver}
        driver_opts:
            onRemove: retain
services:
    app-lb:
        ports:
        - ${http_port}:${http_port}
        labels:
          io.rancher.loadbalancer.target.gitlab: ${domain_app}:${http_port}=80
        tty: true
        image: rancher/load-balancer-service
        links:
        - gitlab:gitlab
        stdin_open: true

    gitlab:
      labels:
           io.rancher.container.start_once: 'true'
      image: gitlab/gitlab-ce
      volumes:
        - gitlab-app-etc:/etc/gitlab
        - git-lab-app-var-log:/var/log/gitlab
        - git-lab-app-var-opt:/var/opt/gitlab
