version: '2'
services:
    app-lb:
        ports:
        - ${http_port}:${http_port}
        labels:
          io.rancher.loadbalancer.target.jenkis: ${domain_app}:${http_port}=8080
          io.rancher.scheduler.affinity:host_label: server=proxy
        tty: true
        image: rancher/load-balancer-service
        links:
        - jenkis:jenkis
        stdin_open: true

    jenkis:
        image: "jenkins:1.651.3"
        labels:
          io.rancher.sidekicks: jenkins-plugins,jenkins-datavolume
          io.rancher.container.hostname_override: container_name
        volumes_from:
          - jenkins-plugins
          - jenkins-datavolume
        entrypoint: /usr/share/jenkins/rancher/jenkins.sh


    jenkins-plugins:
        image: rancher/jenkins-plugins:v0.1.1

    jenkins-datavolume:
        image: "busybox"
        volumes:
          - ${volume_work}:/var/jenkins_home
        labels:
          io.rancher.container.start_once: true
        entrypoint: ["chown", "-R", "1000:1000", "/var/jenkins_home"]
