---
name: Joomla
description: >
  Sistema de Gerenciamento de Conteúdo.
version: v0.1-joomla
category: CMS
maintainer: Luiz Henrique <luiz@madeiracampos.com>
license: GNU GPL v3
projectURL: https://github.com/luiz-madeira/catalogs-rancher
