volumes:
    radarr-config-data:
      driver: ${volumedriver}
    radarr-downloads-data:
      driver: ${volumedriver}
    radarr-movies-data:
      driver: ${volumedriver}


services:
  radarr:
    ports:
      - ${http_port}:7878/tcp
    labels:
      io.rancher.container.hostname_override: container_name
    image: linuxserver/radarr
    volumes:
      - radarr-downloads-data:/downloads
      - radarr-config-data:/config
      - radarr-movies-data:/movies
