version: '2'
catalog:
  name: Radarr
  version: 0.0.1-rancher1
  description: |
    Um gerenciador de filmes rápido, fácil e eficiente.
  minimum_rancher_version: v0.56.0
  maintainer: "Dirceu Silva <contato@dirceusilva.com>"
  questions:
    - variable: "radarr hostname"
      description: "Radarr hostname"
      label: "Hostname:"
      required: true
      default: "radarr.example.com"
      type: "string"
    - variable: "http_port"
      description: "Porta HTTP que será exposta:"
      label: "Porta HTTP:"
      required: true
      default: 8080
      type: "int"
    - variable: "volumedriver"
      description: "Escolha o local do driver de dados.(Option: local or rancher-nfs)"
      label: "Driver de dados:"
      required: true
      default: local
      type: "enum"
      options:
        - local
        - rancher-nfs

radarr:
  scale: 1
  retain_ip: true
  health_check:
    port: 7878
    interval: 30000
    unhealthy_threshold: 3
    strategy: recreate
    response_timeout: 3000
    healthy_threshold: 2
