---
name: TESTE
description: >
  NAO USE
version: 0.0.2-rancher1
category: Exemplo
maintainer: Dirceu Silva <contato@dirceusilva.com>
license: GNU GPL v3
projectURL: https://github.com/contato318/catalogs-rancher-dirceusilva
