.catalog:
  name: Sonnar
  version: 0.0.1-rancher1
  description: |
    Um gerenciador de séries rápido, fácil e eficiente.
  minimum_rancher_version: v0.56.0
  maintainer: "Dirceu Silva <contato@dirceusilva.com>"
  uuid: Sonnar-0
  questions:
    - variable: "Sonnar hostname"
      description: "Sonnar hostname"
      label: "Hostname:"
      required: true
      default: "sonnar.example.com"
      type: "string"
    - variable: "http_port"
      description: "Porta HTTP que será exposta:"
      label: "Porta HTTP:"
      required: true
      default: 8080
      type: "int"
    - variable: "volumedriver"
      description: "Escolha o local do driver de dados.(Option: local or rancher-nfs)"
      label: "Driver de dados:"
      required: true
      default: local
      type: "enum"
      options:
        - local
        - rancher-nfs

sonnar:
  scale: 1
  retain_ip: true
  health_check:
    port: 7878
    interval: 30000
    unhealthy_threshold: 3
    strategy: recreate
    response_timeout: 3000
    healthy_threshold: 2
