version: '2'
services:
    app-lb:
        ports:
        - ${http_port}:${http_port}
        labels:
          io.rancher.loadbalancer.target.wordpress: ${domain_app}:${http_port}=80
          io.rancher.scheduler.affinity:host_label: server=proxy
        tty: true
        image: rancher/load-balancer-service
        links:
        - wordpress:wordpress
        stdin_open: true

    wordpress:
      image: wordpress
      links:
        - db:mysql

    db:
      image: mariadb
      environment:
        MYSQL_ROOT_PASSWORD: ${db_password}
