version: '2'
catalog:
  name: Vote
  version: 0.0.2-rancher1
  description: |
    Um exmeplo de stack para o Rancher.
  minimum_rancher_version: v0.56.0
  maintainer: "Dirceu Silva <contato@dirceusilva.com>"
  questions:
    - variable: "domain_vote"
      description: "Informe a tag (FQDN) para esse serviço (Vote)"
      label: "FQDN Vote:"
      required: true
      default: "vote.app"
      type: "string"
    - variable: "domain_result"
      description: "Informe a tag (FQDN) para esse serviço (Result)"
      label: "FQDN Result:"
      required: true
      default: "result.app"
      type: "string"
    - variable: "http_port"
      description: "Porta HTTP que será exposta:"
      label: "Porta HTTP:"
      required: true
      default: 9096
      type: "int"


services:

    app-lb:
      scale: 1
      load_balancer_config:
        haproxy_config: {}
      health_check:
        port: 42
        interval: 2000
        unhealthy_threshold: 3
        strategy: recreate
        response_timeout: 2000
        healthy_threshold: 2

    result:
      scale: 1
      start_on_create: true

    redis:
      scale: 1
      start_on_create: true

    vote:
      scale: 2
      start_on_create: true

    worker:
      scale: 1
      start_on_create: true

    postgres:
      scale: 1
      start_on_create: true
