version: '2'
catalog:
  name: Joomla
  version: v0.1-joomla
  description: |
    CMS
  minimum_rancher_version: v0.56.0
  maintainer: "Luiz Henrique <luiz@madeiracampos.com>"
  uuid: joomla-0
  questions:
    - variable: "joomladb"
      description: "Senha para o banco de dados"
      label: "Nome do Banco"
      required: true
      default: "joomla"
      type: "string"
    - variable: db_password
      description: "Senha para o banco de dados"
      label: "Password (default: joomla)"
      required: true
      default: "joomla"
      type: "password"
    - variable: "joomla_hostname"
      description: "Joomla hostname"
      label: "Hostname:"
      required: true
      default: "dw.example.com"
      type: "string"
    - variable: "http_port"
      description: "HTTP port to expose on host. Will be used to bind TCP"
      label: "HTTP port:"
      required: true
      default: 80
      type: "string"
      options:
        - local
      
services:
  app-lb:
      scale: 1
      load_balancer_config:
        haproxy_config: {}
      health_check:
        port: 42
        interval: 2000
        unhealthy_threshold: 3
        strategy: recreate
        response_timeout: 2000
        healthy_threshold: 2

  joomla:
    scale: 1
    start_on_create: true
  joomladb:
    scale: 1
    start_on_create: true
    
   